output_files_name: 'inference_on_Solubiltiy'

log_iterations: 100
n_draws: 1000
batch_size: 1
checkpoints_list:
  - ./model_param/model_param.t7
  
embeddings: './embedding_dataset/Train_dataset_emb/t5_embeddings/embeddings_file.h5'
remapping: './embedding_dataset/Train_dataset_emb/remapped_sequences_file.fasta'
key_format: fasta_descriptor



